[build]
builder = "nixpacks"
buildCommand = "cd Backend && npm install"

[deploy]
startCommand = "cd Backend && node src/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
